server:
  port: 9527
spring:
  application:
    name: microServiceCloudGateway
  cloud:
    gateway:
      routes:
        #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
        - id: provider_dept_list_routh #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://MICROSERVICECLOUDPROVIDERDEPT #动态路由，使用服务名代替上面的具体带端口   http://eureka7001.com:9527/dept/list
          predicates:
            #以下是断言条件，必修全部符合条件
            - Path=/dept/list/**   #断言，路径匹配 注意：Path中P为大写
            - Method=GET #只能是GET请求是，才能访问

        - id: provider_dept_get_routh
          uri: lb://MICROSERVICECLOUDPROVIDERDEPT #使用服务名代替上面的具体带端口
          predicates:
            - Path=/get/**
          filters:
            - PrefixPath=/dept #在请求路径上增加一个前缀 /dept

eureka:
  instance:
    instance-id: micro-service-cloud-gateway-9527
    hostname: micro-service-cloud-gateway
  client:
    fetch-registry: true #是否到注册中心搜寻服务：是
    register-with-eureka: true #是否注册到注册中心：是
    service-url:
      defaultZone: http://localhost:7001/eureka/